In [18]:
import pandas as pd
import numpy as np

In [19]:
df=pd.read_csv('./Datasets/play_tennis.csv')

In [20]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

Problem 1
outlook=Sunny,temp=hot,humidity=High,wind=weak
then play or not play

solution 
p(Yes/sunny,hot,high,weak)=P(sunny/Yes)*P(hot/yes)*P(High/yes)*P(weak/Yes)*p(yes)

In [21]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [22]:
#P(Yes)
py=9/14
#P(No)
pn=5/14

In [23]:
print(py,pn)

0.6428571428571429 0.35714285714285715

In [24]:
#outlook

pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [25]:
Pon=0
Prn=2/5
Psn=3/5

Poy=4/9
Pry=3/9
Psy=2/9

In [26]:
#temp

pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [27]:
PcoolNo=1/5
PhotNo=2/5
PmildNo=2/5

PcoolYes=3/9
PhotYes=2/9
PmildYes=4/9

In [28]:
#humidity
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [29]:
PhighNo=4/5
PhighYes=3/9
PnormalNo=1/5
PnormalYes=6/9

In [30]:
#wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [31]:
PstrongNo=3/5
PweakNo=2/5
PstrongYes=3/9
PweakYes=6/9

In [32]:
P_Yes=py*Poy*PhotYes*PhighYes*PweakYes

In [33]:
P_No=pn*Pon*PhotNo*PhighNo*PweakNo

In [34]:
if P_Yes>P_No:
    print('play')
else:
    print('not Play')

play