In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
import pandas as pd

In [2]:
df=pd.read_csv('../Datasets/heart_disease_uci.csv')

In [3]:
df.shape

(920, 16)

In [4]:
df['num'].value_counts()

num
0    411
1    265
2    109
3    107
4     28
Name: count, dtype: int64

In [5]:
df=df.iloc[:,3:]

In [6]:
df.dropna(inplace=True)

In [7]:
df.isnull().sum()

dataset     0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalch      0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
num         0
dtype: int64

In [8]:
df['cp'].value_counts()

cp
asymptomatic       144
non-anginal         83
atypical angina     49
typical angina      23
Name: count, dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=42)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [11]:
ohe=OneHotEncoder()

In [12]:
X_train.head()

,dataset,cp,trestbps,chol,fbs,restecg,thalch,exang,oldpeak,slope,ca,thal
6,Cleveland,asymptomatic,140.0,268.0,False,lv hypertrophy,160.0,False,3.6,downsloping,2.0,normal
185,Cleveland,atypical angina,140.0,195.0,False,normal,179.0,False,0.0,upsloping,2.0,normal
187,Cleveland,atypical angina,160.0,246.0,False,normal,120.0,True,0.0,flat,3.0,fixed defect
147,Cleveland,non-anginal,112.0,250.0,False,normal,179.0,False,0.0,upsloping,0.0,normal
30,Cleveland,typical angina,140.0,239.0,False,normal,151.0,False,1.8,upsloping,2.0,normal

In [13]:
ohe.fit(X_train[['cp','dataset','restecg']])

OneHotEncoder()

In [14]:
X_train_new=ohe.transform(X_train[['cp','dataset','restecg']]).toarray()

In [15]:
X_test_new=ohe.transform(X_test[['cp','dataset','restecg']]).toarray()

In [16]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [17]:
clf1.fit(X_train_new,y_train)
clf2.fit(X_train_new,y_train)

DecisionTreeClassifier()

In [18]:
y_predict1=clf1.predict(X_test_new)
y_predict2=clf2.predict(X_test_new)

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
print(f"The Accuracy score after logistic regression is {accuracy_score(y_test,y_predict1)}")
print(f"The Accuracy score after decision tree classfition is {accuracy_score(y_test,y_predict2)}")

The Accuracy score after logistic regression is 0.5666666666666667
The Accuracy score after decision tree classfition is 0.5666666666666667

In [21]:
from sklearn.metrics import confusion_matrix

In [22]:
confusion_matrix(y_test,y_predict1)

array([[33,  0,  0,  2,  0],
       [ 6,  0,  0,  7,  0],
       [ 3,  0,  0,  2,  0],
       [ 2,  0,  1,  1,  0],
       [ 1,  0,  1,  1,  0]], dtype=int64)

In [26]:
pd.DataFrame(confusion_matrix(y_test,y_predict2),columns=list(range(0,5)))

    0  1  2  3  4
0  33  0  0  2  0
1   6  0  0  7  0
2   3  0  0  2  0
3   2  0  1  1  0
4   1  0  1  1  0